name: Update jdkAnnotations
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  update:
    name: Perform Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: jdkAnnotations
      - name: Checkout IntelliJ
        uses: actions/checkout@v3
        with:
          repository: JetBrains/intellij-community
          path: intellij-community
      - name: Clean current dir
        run: rm -rf jdkAnnotations/jdkAnnotations
      - name: Copy jdkAnnotations
        run: cp -r intellij-community/java/jdkAnnotations jdkAnnotations/jdkAnnotations
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Push updates
        continue-on-error: true
        run: |
          cd jdkAnnotations
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          git add .
          git commit -m "Update for ${{ steps.date.outputs.date }}"
          git push
